LessonDjangoProject/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

LessonDjangoProject/mysite/polls/urls.py
from django.urls import path
from . import views
app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    path('onas/', views.onas, name='onas'),
    path('sponsor/', views.sponsor, name='sponsor'),
    path('seller/', views.seller, name='seller'),
    path('ss/', views.ss, name='ss'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('USA.html', views.usa, name='usa'),
    path('WB.html', views.wb, name='wb'),
    path('GER.html', views.ger, name='ger'),
    path('FRC.html', views.frc, name='frc'),
    path('CH.html', views.ch, name='ch'),
    path('pokupka.html', views.pokupka, name='pokupka'),
]

LessonDjangoProject/mysite/polls/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class Client(AbstractUser):
    # Делаем username необязательным и nullable
    username = models.CharField(max_length=150, null=True, blank=True, unique=False)
    
    # Устанавливаем email как основное поле для аутентификации
    email = models.EmailField(unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []  # username не требуется, так как используем email

    class Meta:
        db_table = 'clients'
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return self.email

class nation(models.Model):
    nation_name = models.CharField(max_length=70)

class tanks(models.Model):
    tanks_title = models.CharField(max_length=70)
    tanks_nation = models.ForeignKey(nation, on_delete=models.CASCADE)
    tanks_cost = models.CharField(max_length=70)

class favorites(models.Model):
    favorites_user = models.ForeignKey(Client, on_delete=models.CASCADE)
    favorites_tanks = models.ForeignKey(tanks, on_delete=models.CASCADE)

class corzine(models.Model):
    corzine_user = models.ForeignKey(Client, on_delete=models.CASCADE)
    corzine_tanks = models.ForeignKey(tanks, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date pokupki')

LessonDjangoProject/mysite/polls/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Client

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = Client
        fields = ('email', 'password1', 'password2')

class LoginForm(AuthenticationForm):
    username = forms.EmailField(label='Email')  # Используем email как username

LessonDjangoProject/mysite/polls/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib import messages
from .forms import RegisterForm, LoginForm
from .models import Client

def index(request):
    return render(request, 'polls/index.html')

def onas(request):
    return render(request, 'polls/onas.html')

def sponsor(request):
    return render(request, 'polls/sponsor.html')

def seller(request):
    return render(request, 'polls/Seller.html')

def ss(request):
    return render(request, 'polls/ss.html')

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = form.cleaned_data['email']  # Используем email как username
            user.save()
            auth_login(request, user)
            return redirect('polls:index')
        else:
            # Вывод ошибок формы
            for field, errors in form.errors.items():
                for error in errors:
                    messages.error(request, f"{field}: {error}")
    else:
        form = RegisterForm()
    return render(request, 'polls/register.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = LoginForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')  # Используем username как email
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=email, password=password)
            if user is not None:
                auth_login(request, user)
                return redirect('polls:index')
        # Вывод ошибок формы
        for error in form.get_invalid_login_error():
            messages.error(request, error)
    else:
        form = LoginForm()
    return render(request, 'polls/login.html', {'form': form})

def usa(request):
    return render(request, 'polls/USA.html')

def wb(request):
    return render(request, 'polls/WB.html')

def ger(request):
    return render(request, 'polls/GER.html')

def frc(request):
    return render(request, 'polls/FRC.html')

def ch(request):
    return render(request, 'polls/CH.html')

def pokupka(request):
    return render(request, 'polls/pokupka.html')

LessonDjangoProject/mysite/polls/templates/polls/CH.html
{% load static %}

<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
  <header class="container-fluid">
    <div class="row">
        <div class="col logo">
            <img src="https://old-wiki.warthunder.ru/images/thumb/3/32/%D0%A2-72%D0%91_%281989%29._%D0%A4%D0%BE%D1%82%D0%BE_3.jpg/240px-%D0%A2-72%D0%91_%281989%29._%D0%A4%D0%BE%D1%82%D0%BE_3.jpg" alt="404 Not Found">
        </div>
        <div class="col-1 navbar">
            <a class="nav-link" href="{% url 'polls:index' %}">На главную</a>
        </div>
    </div>
</header>

  <div id="carousel" class="carousel slide">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div id="first-slide" class="slide-item">
        <p class="text">Т80УМ2</p>
        </div>
      </div>
     
      <div class="carousel-item">
        <div id="twelwe-slide" class="slide-ite     m">
          <p class="text">2С6 Тунгуска</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div class="row">
    <div class="col-lg-4">
        <div class="block d-flex">
            <img class="nav" href="Seller.html" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/ZTZ-99A_MBT_20170716.jpg/300px-ZTZ-99A_MBT_20170716.jpg"alt="icon">
            <div class="block-body">
                <a class="btn btn-link" href="" role="button">Тип 99 (ZTZ-99)</a>
                <p class="block-text">27000000 Рублей</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="block d-flex">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/NORINCO_VT-4_at_IDEX_2017.jpg/320px-NORINCO_VT-4_at_IDEX_2017.jpg"alt="icon">
            <div class="block-body">
                <a class="btn btn-link" href="" role="button">VT-4</a>
                <p class="block-text">1000000000 Рублей</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="block d-flex">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Serbian_HQ-17AE.png/220px-Serbian_HQ-17AE.png"alt="icon">
            <div class="block-body">
                <a class="btn btn-link" href="" role="button">HQ-17</a>
                <p class="block-text">536168145 Рублей</p>
            </div>
        </div>
    </div>
</div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</body>
</html>

LessonDjangoProject/mysite/polls/templates/polls/FRC.html
{% load static %}

<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
  <header class="container-fluid">
    <div class="row">
        <div class="col logo">
            <img src="https://old-wiki.warthunder.ru/images/thumb/3/32/%D0%A2-72%D0%91_%281989%29._%D0%A4%D0%BE%D1%82%D0%BE_3.jpg/240px-%D0%A2-72%D0%91_%281989%29._%D0%A4%D0%BE%D1%82%D0%BE_3.jpg" alt="404 Not Found">
        </div>
        <div class="col-1 navbar">
            <a class="nav-link" href="{% url 'polls:index' %}">На главную</a>
        </div>
    </div>
</header>

  <div id="carousel" class="carousel slide">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div id="first-slide" class="slide-item">
        <p class="text">Т80УМ2</p>
        </div>
      </div>
     
      <div class="carousel-item">
        <div id="twelwe-slide" class="slide-ite     m">
          <p class="text">2С6 Тунгуска</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div class="row">
    <div class="col-lg-4">
        <div class="block d-flex">
            <img class="nav" href="Seller.html" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3bdj1FqwPzK6UaTHKyhwGsOlphsrsxDBnrA&s"alt="icon">
            <div class="block-body">
                <a class="btn btn-link" href="" role="button">leclerc</a>
                <p class="block-text">27000000 Рублей</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="block d-flex">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJ-Cqo-hLNqXhCcw-6--ed5mkQAiiQ6GUrUg&s"alt="icon">
            <div class="block-body">
                <a class="btn btn-link" href="" role="button">AMX 40</a>
                <p class="block-text">1000000000 Рублей</p>
            </div>
        </div>
    </div>
</div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</body>
</html>

LessonDjangoProject/mysite/polls/templates/polls/GER.html
{% load static %}

<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">

</head>
<body>
  <header class="container-fluid">
    <div class="row">
        <div class="col logo">
            <img src="https://old-wiki.warthunder.ru/images/thumb/3/32/%D0%A2-72%D0%91_%281989%29._%D0%A4%D0%BE%D1%82%D0%BE_3.jpg/240px-%D0%A2-72%D0%91_%281989%29._%D0%A4%D0%BE%D1%82%D0%BE_3.jpg" alt="404 Not Found">
        </div>
        <div class="col-1 navbar">
            <a class="nav-link" href="{% url 'polls:index' %}">На главную</a>
        </div>
    </div>
</header>

  <div id="carousel" class="carousel slide">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div id="first-slide" class="slide-item">
        <p class="text">Т80УМ2</p>
        </div>
      </div>
     
      <div class="carousel-item">
        <div id="twelwe-slide" class="slide-ite     m">
          <p class="text">2С6 Тунгуска</p>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

  <div class="row">
    <div class="col-lg-4">
        <div class="block d-flex">
            <img class="nav" href="Seller.html" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/5d/Leopard_2_A7.JPG/300px-Leopard_2_A7.JPG"alt="icon">
            <div class="block-body">
                <a class="btn btn-link" href="" role="button">Leopard 2A7V</a>
                <p class="block-text">27000000 Рублей</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="block d-flex">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Desfile_militar_argentino-2019-6.jpg/274px-Desfile_militar_argentino-2019-6.jpg"alt="icon">
            <div class="block-body">
                <a class="btn btn-link" href="" role="button">TAM 2C</a>
                <p class="block-text">1000000000 Рублей</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="block d-flex">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Wiesel_1_TOW.jpg/220px-Wiesel_1_TOW.jpg"alt="icon">
            <div class="block-body">
                <a class="btn btn-link" href="" role="button">Visel 1a2</a>
                <p class="block-text">536168145 Рублей</p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-4">
        <div class="block d-flex">
            <img class="nav" src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Dutch_Panzerhaubitz_fires_in_Afghanistan.jpg/300px-Dutch_Panzerhaubitz_fires_in_Afghanistan.jpg"alt="icon">
            <div class="block-body">
                <a class="btn btn-link" href="" role="button">PzH 2000</a>
                <p class="block-text">1 000 000 000 Рублей</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="block d-flex">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Waffensystem_Roland_auf_Lkw_15_t_%28FlaRakRad%29.JPG/295px-Waffensystem_Roland_auf_Lkw_15_t_%28FlaRakRad%29.JPG"alt="icon">
            <div class="block-body">
                <a class="btn btn-link" href="" role="button">FlaRakRad Roland</a>
                <p class="block-text">194000000 Рублей</p>
            </div>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="block d-flex">
            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/AIFSV_Side1.png/220px-AIFSV_Side1.png"alt="icon">
            <div class="block-body">
                <a class="btn btn-link" href="" role="button">Begleitpanzer 57</a>
                <p class="block-text">99000000 юань</p>
            </div>
        </div>
    </div>
</div>
</div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</body>
</html>

LessonDjangoProject/mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">

    </head>
    <body>
        <h1>{{ question.question_text }}</h1>
        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text}}</label>
                <br>
            {% endfor %}    
            <input type="submit" value="Отправить>">
        </form>
        </ul>
    </body>
</html>

LessonDjangoProject/mysite/polls/templates/polls/index.html
{% load static %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Мега лендинг</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <header class="container">
        <div class="row">
            <div class="col logo">
                <img src="https://old-wiki.warthunder.ru/images/thumb/3/32/%D0%A2-72%D0%91_%281989%29._%D0%A4%D0%BE%D1%82%D0%BE_3.jpg/240px-%D0%A2-72%D0%91_%281989%29._%D0%A4%D0%BE%D1%82%D0%BE_3.jpg  " alt="404 Not Found">
                <h1>ООО Танковая Биржа</h1>
            </div>
            <div class="col-6 navbar">
                <a class="nav-link text-Gray" href="{% url 'polls:onas' %}">О нас</a>
                <a class="nav-link text-Gray" href="{% url 'polls:sponsor' %}">Спонсоры</a>
                <a class="nav-link text-Gray" href="{% url 'polls:register' %}">Зарегистрироватся</a>
                <a class="nav-link text-Gray" href="{% url 'polls:login' %}">Войти</a>
                <a class="nav-link text-Gray" href="{% url 'polls:pokupka' %}">Купить модель</a>
            </div>
        </div>
    </header>
    <main>
        <section id="info">
            <div class="container-fluid">
                <div class="row">
                        <div class="title">
                            <h2 class="title-header">Все модели танков</h2>
                            <p class="title-text">
                                Какая страна?
                            </p>
                        </div>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="block d-flex">
                            <img class="nav" href="{% url 'polls:seller' %}" src="https://storage.yandexcloud.net/moskvichmag/uploads/2022/06/flag1.png" alt="icon">
                            <div class="block-body">
                                <a class="btn btn-link text-white" href="{% url 'polls:seller' %}" role="button">Русскосоветская</a>
                                <p class="block-text text-white">Танки СССР или России</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="block d-flex">
                            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/250px-Flag_of_the_United_States.svg.png"alt="icon">
                            <div class="block-body">
                                <a class="btn btn-link text-white" href="{% url 'polls:usa' %}" role="button">USA</a>
                                <p class="block-text text-white">Танки Омерики</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="block d-flex">
                            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg/250px-Flag_of_the_United_Kingdom_%283-5%29.svg.png"alt="icon">
                            <div class="block-body">
                                <a class="btn btn-link text-white" href="WB.html" role="button">Британия</a>
                                <p class="block-text text-white">Танки Великобритании</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4">
                        <div class="block d-flex">
                            <img class="nav" src="https://kupit-flag.ru/upload/iblock/6c6/6c6d5997e59a4ecf3c4d5de2ef858cc5.png"alt="icon">
                            <div class="block-body">
                                <a class="btn btn-link text-white" href="GER.html" role="button">Germany</a>
                                <p class="block-text text-white">Танки Германии</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="block d-flex">
                            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Ensign_of_France.svg/200px-Ensign_of_France.svg.png"alt="icon">
                            <div class="block-body">
                                <a class="btn btn-link text-white" href="FRC.html" role="button">Francia</a>
                                <p class="block-text text-white">Танки Франции</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="block d-flex">
                            <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/800px-Flag_of_the_People%27s_Republic_of_China.svg.png"alt="icon">
                            <div class="block-body">
                                <a class="btn btn-link text-white" href="CH.html" role="button">CHINA</a>
                                <p class="block-text text-white">Танки Китая</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <footer>
    </footer>
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <!-- <script type="text/javascript" src="header.js"></script> -->
</body>
</html>

LessonDjangoProject/mysite/polls/templates/polls/login.html
{% load static %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Вход</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styler.css' %}">
</head>
<body>
    <header class="header">
        <div class="logo">
            <img src="https://old-wiki.warthunder.ru/images/thumb/3/32/%D0%A2-72%D0%91_%281989%29._%D0%A4%D0%BE%D1%82%D0%BE_3.jpg/240px-%D0%A2-72%D0%91_%281989%29._%D0%A4%D0%BE%D1%82%D0%BE_3.jpg" alt="Logo">
        </div>
        <div class="navbar">
            <a class="nav-link" href="{% url 'polls:index' %}">Назад</a>
        </div>
    </header>

    <div class="login-container">
        <h2>Вход</h2>
        {% if messages %}
            <div class="alert alert-danger">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <form method="post" action="{% url 'polls:login' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="login-btn">Войти</button>
        </form>
    </div>
</body>
</html>

LessonDjangoProject/mysite/polls/templates/polls/register.html
{% load static %}
{% block content %}

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'styler.css' %}">
</head>

<body>
    <header class="header">
        <div class="logo">
            <img src="https://old-wiki.warthunder.ru/images/thumb/3/32/%D0%A2-72%D0%91_%281989%29._%D0%A4%D0%BE%D1%82%D0%BE_3.jpg/240px-%D0%A2-72%D0%91_%281989%29._%D0%A4%D0%BE%D1%82%D0%BE_3.jpg" alt="Logo">
        </div>
        <div class="navbar">
            <a class="nav-link" href="{% url 'polls:index' %}">Назад</a>
        </div>
    </header>

    <div class="registration-container">
        <div class="registration-form">
            <h2 class="form-title">Регистрация</h2>
            
            {% if messages %}
                <div class="alert alert-danger">
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                </div>
            {% endif %}

            <form method="post" class="form-signup" action="{% url 'polls:register' %}">
                {% csrf_token %}
                
                <div class="form-group">
                    <label for="{{ form.email.id_for_label }}">Email:</label>
                    {{ form.email }}
                </div>

                <div class="form-group">
                    <label for="{{ form.password1.id_for_label }}">Пароль:</label>
                    {{ form.password1 }}
                </div>

                <div class="form-group">
                    <label for="{{ form.password2.id_for_label }}">Подтверждение пароля:</label>
                    {{ form.password2 }}
                </div>

                <button type="submit" class="submit-btn">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</body>
{% endblock %}